import os 

# data path management
PROJECT_ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TRAIN_DATA_PATH = PROJECT_ROOT_DIR + "/data/train.csv"
TEST_DATA_PATH = PROJECT_ROOT_DIR + "/data/test.csv"

# Feature engineering cols

CAT_COLS = ['Gender', 'State', 'Specialty']
TARGET = ['Opioid.Prescriber']
NUM_COLS = ['ABILIFY', 'ACETAMINOPHEN.CODEINE', 'ACYCLOVIR', 'ADVAIR.DISKUS', 'AGGRENOX', 
'ALENDRONATE.SODIUM', 'ALLOPURINOL', 'ALPRAZOLAM', 'AMIODARONE.HCL', 'AMITRIPTYLINE.HCL', 
'AMLODIPINE.BESYLATE', 'AMLODIPINE.BESYLATE.BENAZEPRIL', 'AMOXICILLIN', 'AMOX.TR.POTASSIUM.CLAVULANATE', 
'AMPHETAMINE.SALT.COMBO', 'ATENOLOL', 'ATORVASTATIN.CALCIUM', 'AVODART', 'AZITHROMYCIN', 'BACLOFEN', 
'BD.ULTRA.FINE.PEN.NEEDLE', 'BENAZEPRIL.HCL', 'BENICAR', 'BENICAR.HCT', 'BENZTROPINE.MESYLATE', 
'BISOPROLOL.HYDROCHLOROTHIAZIDE', 'BRIMONIDINE.TARTRATE', 'BUMETANIDE', 'BUPROPION.HCL.SR', 'BUPROPION.XL', 
'BUSPIRONE.HCL', 'BYSTOLIC', 'CARBAMAZEPINE', 'CARBIDOPA.LEVODOPA', 'CARISOPRODOL', 'CARTIA.XT', 'CARVEDILOL', 
'CEFUROXIME', 'CELEBREX', 'CEPHALEXIN', 'CHLORHEXIDINE.GLUCONATE', 'CHLORTHALIDONE', 'CILOSTAZOL', 'CIPROFLOXACIN.HCL', 
'CITALOPRAM.HBR', 'CLINDAMYCIN.HCL', 'CLOBETASOL.PROPIONATE', 'CLONAZEPAM', 'CLONIDINE.HCL', 'CLOPIDOGREL', 
'CLOTRIMAZOLE.BETAMETHASONE', 'COLCRYS', 'COMBIVENT.RESPIMAT', 'CRESTOR', 'CYCLOBENZAPRINE.HCL', 'DEXILANT', 
'DIAZEPAM', 'DICLOFENAC.SODIUM', 'DICYCLOMINE.HCL', 'DIGOX', 'DIGOXIN', 'DILTIAZEM.24HR.CD', 'DILTIAZEM.24HR.ER', 
'DILTIAZEM.ER', 'DILTIAZEM.HCL', 'DIOVAN', 'DIPHENOXYLATE.ATROPINE', 'DIVALPROEX.SODIUM', 'DIVALPROEX.SODIUM.ER', 
'DONEPEZIL.HCL', 'DORZOLAMIDE.TIMOLOL', 'DOXAZOSIN.MESYLATE', 'DOXEPIN.HCL', 'DOXYCYCLINE.HYCLATE', 'DULOXETINE.HCL', 
'ENALAPRIL.MALEATE', 'ESCITALOPRAM.OXALATE', 'ESTRADIOL', 'EXELON', 'FAMOTIDINE', 'FELODIPINE.ER', 'FENOFIBRATE', 
'FENTANYL', 'FINASTERIDE', 'FLOVENT.HFA', 'FLUCONAZOLE', 'FLUOXETINE.HCL', 'FLUTICASONE.PROPIONATE', 'FUROSEMIDE', 
'GABAPENTIN', 'GEMFIBROZIL', 'GLIMEPIRIDE', 'GLIPIZIDE', 'GLIPIZIDE.ER', 'GLIPIZIDE.XL', 'GLYBURIDE', 'HALOPERIDOL', 
'HUMALOG', 'HYDRALAZINE.HCL', 'HYDROCHLOROTHIAZIDE', 'HYDROCODONE.ACETAMINOPHEN', 'HYDROCORTISONE', 'HYDROMORPHONE.HCL', 
'HYDROXYZINE.HCL', 'IBANDRONATE.SODIUM', 'IBUPROFEN', 'INSULIN.SYRINGE', 'IPRATROPIUM.BROMIDE', 'IRBESARTAN', 
'ISOSORBIDE.MONONITRATE.ER', 'JANTOVEN', 'JANUMET', 'JANUVIA', 'KETOCONAZOLE', 'KLOR.CON.10', 'KLOR.CON.M10', 
'KLOR.CON.M20', 'LABETALOL.HCL', 'LACTULOSE', 'LAMOTRIGINE', 'LANSOPRAZOLE', 'LANTUS', 'LANTUS.SOLOSTAR', 
'LATANOPROST', 'LEVEMIR', 'LEVEMIR.FLEXPEN', 'LEVETIRACETAM', 'LEVOFLOXACIN', 'LEVOTHYROXINE.SODIUM', 'LIDOCAINE', 
'LISINOPRIL', 'LISINOPRIL.HYDROCHLOROTHIAZIDE', 'LITHIUM.CARBONATE', 'LORAZEPAM', 'LOSARTAN.HYDROCHLOROTHIAZIDE', 
'LOSARTAN.POTASSIUM', 'LOVASTATIN', 'LOVAZA', 'LUMIGAN', 'LYRICA', 'MECLIZINE.HCL', 'MELOXICAM', 'METFORMIN.HCL', 
'METFORMIN.HCL.ER', 'METHADONE.HCL', 'METHOCARBAMOL', 'METHOTREXATE', 'METHYLPREDNISOLONE', 'METOCLOPRAMIDE.HCL', 
'METOLAZONE', 'METOPROLOL.SUCCINATE', 'METOPROLOL.TARTRATE', 'METRONIDAZOLE', 'MIRTAZAPINE', 'MONTELUKAST.SODIUM', 
'MORPHINE.SULFATE', 'MORPHINE.SULFATE.ER', 'MUPIROCIN', 'NABUMETONE', 'NAMENDA', 'NAMENDA.XR', 'NAPROXEN', 'NASONEX', 
'NEXIUM', 'NIACIN.ER', 'NIFEDICAL.XL', 'NIFEDIPINE.ER', 'NITROFURANTOIN.MONO.MACRO', 'NITROSTAT', 'NORTRIPTYLINE.HCL', 
'NOVOLOG', 'NOVOLOG.FLEXPEN', 'NYSTATIN', 'OLANZAPINE', 'OMEPRAZOLE', 'ONDANSETRON.HCL', 'ONDANSETRON.ODT', 'ONGLYZA', 
'OXCARBAZEPINE', 'OXYBUTYNIN.CHLORIDE', 'OXYBUTYNIN.CHLORIDE.ER', 'OXYCODONE.ACETAMINOPHEN', 'OXYCODONE.HCL', 
'OXYCONTIN', 'PANTOPRAZOLE.SODIUM', 'PAROXETINE.HCL', 'PHENOBARBITAL', 'PHENYTOIN.SODIUM.EXTENDED', 'PIOGLITAZONE.HCL', 
'POLYETHYLENE.GLYCOL.3350', 'POTASSIUM.CHLORIDE', 'PRADAXA', 'PRAMIPEXOLE.DIHYDROCHLORIDE', 'PRAVASTATIN.SODIUM', 
'PREDNISONE', 'PREMARIN', 'PRIMIDONE', 'PROAIR.HFA', 'PROMETHAZINE.HCL', 'PROPRANOLOL.HCL', 'PROPRANOLOL.HCL.ER', 
'QUETIAPINE.FUMARATE', 'QUINAPRIL.HCL', 'RALOXIFENE.HCL', 'RAMIPRIL', 'RANEXA', 'RANITIDINE.HCL', 'RESTASIS', 
'RISPERIDONE', 'ROPINIROLE.HCL', 'SEROQUEL.XR', 'SERTRALINE.HCL', 'SIMVASTATIN', 'SOTALOL', 'SPIRIVA', 
'SPIRONOLACTONE', 'SUCRALFATE', 'SULFAMETHOXAZOLE.TRIMETHOPRIM', 'SUMATRIPTAN.SUCCINATE', 'SYMBICORT', 'SYNTHROID', 
'TAMSULOSIN.HCL', 'TEMAZEPAM', 'TERAZOSIN.HCL', 'TIMOLOL.MALEATE', 'TIZANIDINE.HCL', 'TOLTERODINE.TARTRATE.ER', 
'TOPIRAMATE', 'TOPROL.XL', 'TORSEMIDE', 'TRAMADOL.HCL', 'TRAVATAN.Z', 'TRAZODONE.HCL', 'TRIAMCINOLONE.ACETONIDE', 
'TRIAMTERENE.HYDROCHLOROTHIAZID', 'VALACYCLOVIR', 'VALSARTAN', 'VALSARTAN.HYDROCHLOROTHIAZIDE', 'VENLAFAXINE.HCL', 
'VENLAFAXINE.HCL.ER', 'VENTOLIN.HFA', 'VERAPAMIL.ER', 'VESICARE', 'VOLTAREN', 'VYTORIN', 'WARFARIN.SODIUM', 'XARELTO', 
'ZETIA', 'ZIPRASIDONE.HCL', 'ZOLPIDEM.TARTRATE']

BINARY_CAT_VARIABLES = ['Gender']
MULTI_CAT_VARIABLES = ['State', 'Specialty']
DROP_COLS = ['NPI','Credentials']


# model saving
MODEL_SAVE = PROJECT_ROOT_DIR + "/notebooks/trained_models/model.joblib"